---
telegraf_output:
  - type: influxdb
    config:
      - urls = ["https://influx-server.weslyg.ru"]
      - database = "wazuh"
      - precision = "s"
      - password = "{{ secret_influx_password }}"
      - username = "reporter"

package_list:
  - git
  - nano
  - curl
  - wget
  - nmap
  - htop
  - firewalld
  - python3
  - python3-dev
  - python3-pip

alias_block: |
  alias d='docker'
  alias dc='docker-compose'
  alias tailf='tail -f'

port_opened:
  - 9500/tcp
  - 9000/tcp
  - 5601/tcp
