---
package_list:
  - git
  - nano
  - curl
  - wget
  - nmap
  - htop
  - python3
  - python3-dev
  - python3-pip

# pip_package_list:
#   - docker-compose

alias_block: |
  alias d='docker'
  alias dc='docker-compose'
